[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
zerocopy = { version = "0.7", features = ["derive"] }

[[bin]]
name = "kernel"
path = "main.rs"
test = false
bench = false
