[target.riscv64gc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tkernel.ld",
  "-C", "panic=abort",
  "-C", "link-arg=-Map=kernel.map",
]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "riscv64gc-unknown-none-elf"
